title: "Matthew Freeman"
description: "My personal website"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

header:
  nav: main

collections:
  projectsgis:
    output: true

collections:
  projectsarduino:
    output: true
    
home:
  show_posts: false
